version: '3.6'

services:
  simple-monitor:
    image: ubuntu:focal
    container_name: simple-monitor
    environment:
      - TZ=America/Denver
    ports: 
      - "8080:80"
    volumes:
      - ./:/workspace
      - monitor_data:/monitor_data
    tty: true
    stdin_open: true
    command: ["/workspace/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    restart: unless-stopped

volumes:
  monitor_data:
