version: '3.6'

services:
  simple-monitor:
    image: ubuntu:focal
    container_name: simple-monitor
    environment:
      - TZ=America/Denver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    tty: true
    stdin_open: true
    command: ["/workspace/deployer.sh"]
    logging:
        options:
            max-size: 1g
    restart: unless-stopped
