version: '3'

services:
  simple-monitor:
    image: ubuntu:focal
    container_name: simple-monitor
    environment:
      - TZ=America/Denver
    ports: 
      - "8080:80"
    volumes:
      - monitor_workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    tty: true
    stdin_open: true
    command: ["/workspace/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    restart: unless-stopped

  volumes: 
    - name: monitor_workspace
      driver: local